request:
  method: GET
  reg_url:
    - /sp\?.+seller=[A-Z0-9]{5,}
  reg_match:
    - sellerName
  params:
  headers:
    accept-language: en_US,en;q=0.9
    cookie: session-id=136-2173606-0042214; i18n-prefs=USD; sp-cdn="L5Z9:SG"; ubid-main=133-4371130-6431956; lc-main=en_US; session-token=S25s/P5UswrDX05nVscuiDvFKHbzEY2EW/3utQrRxxp2nKUC271/AG3IWvN1Rqi7IudXQslFfTlkKsbJNSzrBpQo5qpHeWKbZ+dtM3bs98PTh++DDQC+d0UU44r0dmVbTdta7puF88lL8qnxrvHAZw17xAJIis7EMgCvbFbgyuJpltWdpJ/qpavuAG7I1WCq/QI//uH0lnim5aVCb01yNYdPQJB9VMF5; skin=noskin; session-id-time=2082787201l
dataFields:
  -
    tag: language
    name: 语言
    matchIdx: 1
    matchReg: '"(.+?)"'
    regexp:
      - 'language:[\s]?"(.+?)"'
    type: TEXT
  -
    tag: seller_name
    name: 卖家名称
    xPath:
      - //*[@id='sellerName']
      - //*[@id='sellerName-rd']
    type: TEXT
  -
    tag: star
    name: 卖家星级
    matchIdx: -1
    matchReg: '\d+\.\d+|\d+'
    xPath:
      - //div[contains(@id, 'seller-feedback-summary')]//i/span
    type: TEXT
  -
    tag: favorite
    name: 正面评价
    matchIdx: -1
    matchReg: '\d+%|\d+％'
    xPath:
      - //div[contains(@id, 'seller-feedback-summary')]//a/b
    type: TEXT
  -
    tag: rating
    name: 评星级数
    matchIdx: 1
    matchReg: '\(([\d]+)'
    xPath:
      - //div[contains(@id, 'seller-feedback-summary')]//a
    type: TEXT
  -
    tag: introduce
    name: 卖家介绍
    xPath:
      - //span[@id='about-seller-expanded']
      - //span[@id='about-seller-text']
      - //div[@id='spp-expander-about-seller']//div[contains(@class, 'spp-expander-more-content')]
    type: TEXT
  -
    tag: shipping
    name: 物流规则
    xPath:
      - //div[@id='shippingRatesFeature']
      - //*[@id="spp-accordion-shipping-policies"]/div/div
      - //*[@id='shipping-policies']
    type: TEXT
  -
    tag: business_name
    name: 公司名称
    xPath:
      - //*[@id="page-section-detail-seller-info"]/div/div/div/div[2]/span[2]
    type: TEXT
  -
    tag: business_address
    name: 公司地址
    xPath:
      - //*[@id="page-section-detail-seller-info"]/div/div/div
    type: TEXT
    children:
        -
          tag: business_address
          name: 公司地址
          cssPath:
            - '.indent-left span'
          type: LIST
  -
    tag: feedback
    name: 意见反馈
    xPath:
      - //table[@id='feedback-summary-table']
    type: TEXT
    children:
      - tag: positive
        name: 好评
        xPath:
          - //*[@id="feedback-summary-table"]/tbody/tr[2]/td[contains(@class, 'a-text-right')]
        type: LIST
      - tag: neutral
        name: 中评
        xPath:
          - //*[@id="feedback-summary-table"]/tbody/tr[3]/td[contains(@class, 'a-text-right')]
        type: LIST
      - tag: negative
        name: 差评
        xPath:
          - //*[@id="feedback-summary-table"]/tbody/tr[4]/td[contains(@class, 'a-text-right')]
        type: LIST
      - tag: count
        name: 计数
        xPath:
          - //*[@id="feedback-summary-table"]/tbody/tr[5]/td[contains(@class, 'a-text-right')]
        type: LIST
  -
    tag: contact
    name: 联系电话
    xPath:
      - //span[@id='seller-contact-phone']
    type: TEXT