method: get
params:
headers:
  -
    key: cache-control
    value: max-age=0
  -
    key: accept-language
    value: zh-CN,zh;q=0.9
pageInfo:
  pageCssPath:
    - .a-section.a-text-center.s-pagination-container
  nextCssPath:
    - span.s-pagination-strip a.s-pagination-item.s-pagination-next
  endCssPath:
    - .s-pagination-item.s-pagination-next.s-pagination-disabled[aria-disabled="true"]
  indexCssPath:
    - .s-pagination-container span.s-pagination-item.s-pagination-selected
  listCssPath:
    - '[data-component-type="s-search-result"]'
  keyWordCssPath:
    - '[data-component-type="s-result-info-bar"] .a-color-state.a-text-bold'
  pageEvent:
    - click
dataFields:
  -
    tag: title
    name: 标题节点
    xPath:
      - //*[@id="t_41772a550102zami"]
    cssPath:
      - #t_41772a550102zami
    type: TEXT
  -
    tag: content
    name: 内容节点
    xPath:
      - //*[@id="sina_keyword_ad_area2"]/div[2]
    cssPath:
      - #sina_keyword_ad_area2
    type: TEXT
  -
    tag: like
    name: 喜欢节点
    xPath:
      - //*[@id="dbox2_41772a550102zami"]
    cssPath:
      - #dbox2_41772a550102zami
    type: TEXT
  -
    tag: goldpen
    name: 赠金笔
    xPath:
      - //*[@id="goldPan-num"]
    cssPath:
      - #goldPan-num
    type: TEXT